name: If push to the main, deploy it

on:
  push:
    branches:
      - main
    # paths:
    #   - "canbus-web/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        TEAM_NAME: woowasiblings
        APP_NAME: canbus-web
        APP_ENV: canbus-web-env
        RG_NAME: rg-2024-Woowa-Siblings

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: ${{ github.workspace }}/$APP_NAME
          acrName: $TEAM_NAME
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: $APP_NAME
          containerAppEnvironment: $APP_ENV
          resourceGroup: $RG_NAME
          imageToBuild: $TEAM_NAME.azurecr.io/$APP_NAME:${{ github.sha }}
          dockerfilePath: Dockerfile

      - name: Azure Container Apps Ingress Setting
        run: az containerapp ingress update --name $APP_NAME --resource-group $RG_NAME --target-port 3000 --allow-insecure
