name: If push to the main, deploy it

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "canbus-web/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        APP_NAME: ${{ secrets.SERVICE_NAME }}-web
        APP_ENV: ${{ secrets.SERVICE_NAME }}-web-env

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: ${{ github.workspace }}/${{ env.APP_NAME }}
          acrName: ${{ secrets.ACR_NAME }}
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: ${{ env.APP_NAME }}
          containerAppEnvironment: ${{ env.APP_ENV }}
          resourceGroup: ${{ secrets.RG_NAME }}
          imageToBuild: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          dockerfilePath: Dockerfile

      - name: Azure Container Apps Ingress Setting
        run: az containerapp ingress update --name ${{ env.APP_NAME }} --resource-group ${{ secrets.RG_NAME }} --target-port 3000 --allow-insecure
